name: "TDOAuth CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Example:
    name: Example Project (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod install
        run: pod install --project-directory=Example

      - name: Build Project
        uses: sersoft-gmbh/xcodebuild-action@v1.8.0
        with:
          workspace: Example/TDOAuth.xcworkspace
          scheme: TDOAuth_iOS
          destination: name=iPhone 13 Pro
          action: test
          
  Pods:
    name: Cocoapods Lint (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod lib lint dynamic-framework
        run: pod lib lint --fail-fast

      - name: Run pod lib lint static-framework
        run: pod lib lint --fail-fast --use-libraries --use-modular-headers
          
  SwiftPM:
    name: SwiftPM (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable 

      - name: Build
        run: swift build
